apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus-uid
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Elasticsearch
    type: elasticsearch
    uid: elasticsearch-uid
    access: proxy
    url: http://elasticsearch:9200
    database: "eduquiz-logs-*"
    jsonData:
      index: "eduquiz-logs-*"
      timeField: "@timestamp"
      esVersion: "8.11.0"
      maxConcurrentShardRequests: 5
      logMessageField: "message"
      logLevelField: "level"
      includeFrozen: false
    editable: false
